name: Build CI Service Images
run-name: Build CI Service Images
on:
  push:
    paths:
      - .github/services/Dockerfile.*
      - examples/etcd/certs/*.pem
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gravitational/ci-etcd
  ETCD_VERSION: 3.3.9

jobs:
  build:
    name: Build CI Services Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build etcd image
        id: docker_build
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: ${{ github.workspace }}
          file: .github/services/Dockerfile.etcd
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.ETCD_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ETCD_VERSION=${{ env.ETCD_VERSION }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
